# Generated by Django 5.2 on 2025-05-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_phone_number_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.type'),
        ),
    ]
