# Generated by Django 5.2 on 2025-05-06 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('zipcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('rooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('size', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('list_date', models.DateField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipcode.zipcode')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.type')),
            ],
        ),
    ]
