# Generated by Django 5.2 on 2025-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyimage_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyimage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('property',), name='only_one_main_image_per_property'),
        ),
    ]
