# Generated by Django 5.2 on 2025-05-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_propertyimage_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='seller',
        ),
    ]
