# Generated by Django 5.2 on 2025-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_property_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seller_id',
            field=models.IntegerField(default=1),
        ),
    ]
